### ISSUE TITLE
Limit number of assets in a channel

### ISSUE THREAD

**Issue by HeikoFisch** [connext/vector#139]
In the adjudicator, we defund assets in a loop. This means we have to restrict the number of assets simultaneously held in a channel.
The gas for the actual transfer is currently limited to 10k for Ether and 100k for ERC20s (which might be a bit too generous). Taking into account that the actual transfer can fail, which will make the amount emergency-withdrawable, and that we have quite a few calls and storage reads in addition to that, I'd ballpark the maximum possible gas consumption per asset and recipient at around 150k; let's be generous and say 200k. With two channel participants, we finally arrive at 400k per asset (again, ballparked).
Based on these estimates, I'd suggest to limit the number of assets per channel to 5.

This number can be raised considerably (2-3x) if we move to a pure withdrawal pattern. Reducing the amount of gas we provide the actual transfer call with would also allow us to increase the limit somewhat. On the other hand (and IIRC), usage patterns of the past show that we rarely need more than two assets per channel.

**Comment by LayneHaber** [comment]
Defund accepts array of assetIds, circumventing this issue
