### ISSUE TITLE
Allow different log levels, non-verbose `info` by default

### ISSUE THREAD

**Issue by kilrau** [connext/vector#171]
**Is your feature request related to a problem? Please describe.**
We had the issue with indra/rest api client logs that they were too verbose by default, adding several GBs to the log file per week

**Describe the solution you'd like**
Different log levels: `info`, `debug`, `trace`. Defaulting to `info` which shouldn't add more than some 10MB/week and ideally also support roll over to new log files and automatically zip old ones, just like lnd does.

**Describe alternatives you've considered**
N/A

**Comment by rhlsthrm** [comment]
We already support these log levels in the `node.config.json`: https://connext.github.io/vector/node/configure/#node-configuration-api

We can look into the default log level and how much it logs and the rollover features.
