### ISSUE TITLE
[contracts] determine timeouts via `block.timestamp` vs `block.number`

### ISSUE THREAD

**Issue by bohendo** [connext/vector#172]
```
  function inDefundPhase() internal view returns (bool) {
    return channelDispute.consensusExpiry <= block.number && block.number < channelDispute.defundExpiry;
  }
```
Why compare against block numbers while determining timeouts? Better UX would be to use people-time and compare against block.timestamp
Then we can say "The timeout is 1 hour" instead of "The timeout is between 45 mins and 1 hour 15 mins but this is only a confidence interval bc mining isn't deterministic"

In general, block numbers are "safer" than block times, because they are completely determined, i.e. they have to be consecutive numbers. The block times are much more vague; the yellow paper doesn't say much about them, and the miners/nodes have more freedom what they write/accept there.

[From a similar Q on stack exchange:](https://ethereum.stackexchange.com/a/428):
> Block times are subject to the following constraints:
> - If you stamp your block with a time too far in the future, no one else will build on it (miners will not build on a block timestamped "from the future").
> - Your block time cannot be stamped with an earlier time than its parent.
> - Difficulty is kept lowest (best deal for miners) by not stamping blocks as earlier than they actually occur.
> Taken together, these factors suggest that most blocks produced by small hashrate miners who are not trying to manipulate anything will be pretty close to accurate. However, it is trivial for a more powerful miner to manipulate timestamps over short periods, especially if there is something to be gained by doing this.

[Game theory of blocktimes](https://ethereum.stackexchange.com/a/5932)
[Statistical analysis of block timestamps](https://ethereum.stackexchange.com/a/5905)

The greatest difference between two block timestamps in the history of eth was 155s or 2.5 minutes. Idk if this was bc the miners fell asleep or just a random fluke or what, but if this was funny business, it represents one estimate for what a timestamp manipulation black swam might look like. Not catastrophic tbh. If a timeout window abruptly closed 2 mins early, that's not super different than submiting a tx as usual & a gas fees spike makes your tx get mined 2 mins later than expected.

Ultimately, this seems to be a decision between:
 A. good happy-case UX, slight danger from black-swans
 B. bad happy-case UX, no black-swan danger
There can't really be a "correct" answer here, it seems like more of a value judgement

**Comment by LayneHaber** [comment]
Hm, I am actually in favor of this -- it would help with the complexity around dealing with cross chain block times a *lot* which is important
