### ISSUE TITLE
Convert spacefold to use vector

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector#187]
Task:

- Connect to browser Node
- [x]  Using prod iframe url

- Setup Channel
- [x]  Use browser SDK setup() function
- [x]  Setup channel for each chain

- Deposit
- [x]  Remove mint
- [x]  create a deposit function using ethers
- [x]  UI for deposit function

- Transfer:  Make a transfer to yourself on a different chain
- [x]  make a conditional transfer

- withdraw
- [x]  auto withdraw.

**Comment by sanchaymittal** [comment]
Goals for this pr are achieved, ready with a hosted demo.
