### ISSUE TITLE
[feature request] add possibility to get all channels info in one api call.

### ISSUE THREAD

**Issue by RostyslavAntonyshyn** [connext/vector#205]
**Is your feature request related to a problem? Please describe.**

For now to get all channels info we need to make `publicIdentifier/channels` call, and then get info for each channel separately by it's ID.

**Describe the solution you'd like**

Would be very helpful to have something like `<publicIdentifier>/getallchannels` to receive :
```
[
"channelID1" :
{info},
"channelID2" :
{info},
]
```

**Comment by LayneHaber** [comment]
There is an API to get all the `multisigAddress`es that are open, but returning all the channel information would be a prohibitively large response in many cases
