### ISSUE TITLE
[ops] Build ARM docker images

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector#217]
Supposedly is easy if you use GitHub actions.

**Comment by bohendo** [comment]
More info: https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee

**Comment by bohendo** [comment]
Another good resource: https://wiki.ubuntu.com/ARM64/QEMU

**Comment by bohendo** [comment]
Seems like it's not possible for me to test this locally bc I don't have any ARM devices: https://stackoverflow.com/a/52793714
If it's only possible to tweak/check this via github actions then this will take some time to develop.

**Comment by bohendo** [comment]
My naive attempt at generating a prisma client on ARM failed, this issue has a good discussion of the issue: https://github.com/prisma/prisma/issues/3713

On 7th Dec, 2020 a prisma teammate said ["We are currently working on providing binaries for ARM ... This was quite some work but we are nearing the finish line"](https://github.com/prisma/prisma/issues/3713#issuecomment-739904391) so might be worth waiting for this to be resolved.

If want to build these binaries ourselves, the [prisma-arm64 repo](https://github.com/jcmcneal/prisma-arm64) and prisma's [engine building guide](https://github.com/prisma/prisma-engines#building-prisma-engines) would be good resources to look at
