### ISSUE TITLE
Add "ERC-like" process for adding transfers

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector#239]
Use "VRC" (?) identifiers for transfer names to guarantee uniqueness across chains.

**Comment by sanchaymittal** [comment]
@rhlsthrm How about `VIPs`? This could be for any proposal requested to vector, just not limited to transfer names. Like Offline payments and any other major update.

**Comment by rhlsthrm** [comment]
I like `VIP`! Nice double meaning.
