### ISSUE TITLE
[router] Allow collateralization target to be set to 0 and fix reclaim thresholds

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#298]
- [x]  Allow for target to be set to 0 - this makes sense because we *always* want to inflight collateralize for now
- [x]  Right now, collateralization logic errors if the `target + transfer amount > reclaim threshold`. This is incorrect. It should only error if `target > reclaim threshold`, because we should always allow a large inflight collateralization of transfer amount

**Comment by LayneHaber** [comment]
Fixed
