### ISSUE TITLE
Need Better Ways of Looking up Completed Transfers

### ISSUE THREAD

**Issue by HyperCharlie** [connext/vector#331]
For the Hypernet Protocol, but I suspect other use cases as well, we are using multiple transfers for a single "payment". The state of the payment depends on the state of the constituent transfers. The issue is that there are only two ways to get transfers- getting all the active transfers (great) and getting a transfer by it's ID. The problem with the second method is that unless you implement external persistence, you have no way of knowing the ID. External persistence brings a whole host of other issues, so it would be nice to not have to go that route.

For us, an easy solution is to be able to query for all transactions, open or closed, after a certain date. We start by getting all the open transfers, sort and get the earliest one, and then query for all transfers after that date, and we are assured to have all the relevant transfers. So a method on the node getTransfersAfterDate(firstDate), or getTransfersInRange(startDate, endDate?) would be ideal. Even if these methods just return an array of transfer IDs that's fine, but would just required us to do more lookups.

**Comment by HyperCharlie** [comment]
I found an issue with this PR now that I've started to try and use it- it doesn't look like the getTransfers() method was added to the browser node itself! Looking in the PR and in the code as pulled from NPM, I don't see anywhere in the browser node where this method is exposed.

**Comment by rhlsthrm** [comment]
Ridiculous, I added the store method but didn't actually expose the interfaces! Will fix this today!
