### ISSUE TITLE
Investigate why reclaim withdrawal commitments are created but not submitted to chain

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#357]
On the DG router, sender-side funds are being correctly reclaimed and withdrawn by the router. However, the withdrawal commitments are not actually being submitted to chain.

This ties into https://github.com/connext/vector/issues/354 as a reference for the desired outcome (which is similar to what's happening now).

It also ties into https://github.com/connext/vector/issues/358 as a potential solution for any hanging commitments after we debug this issue.

**Comment by LayneHaber** [comment]
See [here](https://github.com/connext/vector/blob/e8329c50aed2322140df9005750b901d99ab9825/modules/engine/src/listeners.ts#L701-L707)
