### ISSUE TITLE
[router, config] Scope and implement fees

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#360]
We need to implement at least some basic fee capture mechanisms to pass costs of operating a router down to the end user. 

Right now we have: 
(1) Spreads on swap rates
(2) Fees on withdraw

We probably also need:
- A way to charge fees during transfers (e.g. xud)
- A way to estimate fees and show that to the user in the UI

We can subsidize the cost of going from Ethereum -> L2, but will likely need to show at least *some* fees for L2 -> Ethereum given where gas is at.

**Comment by rhlsthrm** [comment]
Spec: https://www.notion.so/connext/Router-v0-Fees-9976c352941a434794b2d8de9a54533a
