### ISSUE TITLE
[types] Make timeouts actually optional

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#378]
Timeouts on `setup` and `create` should be optional but aren't. We shouldn't be having users define their own timeouts unless they know exactly what they're doing.

**Comment by rhlsthrm** [comment]
To add to this issue, I found that withdraw param converter isn't actually passing the timeout through so even if it gets set it gets set to the default transfer timeout.

**Comment by jakekidd** [comment]
While I haven't handled second issue mentioned by @rhlsthrm above, here is PR: https://github.com/connext/vector/pull/463
