### ISSUE TITLE
Messaging server HA + monitoring

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector#389]
Messaging is a critical piece of infrastructure that needs to be highly-available and monitored. The messaging server consists of:
- Auth service
- NATS server
- Proxy

**Comment by rhlsthrm** [comment]
Currently, this is all run on a single host. We can split this up so that the auth service is scaled horizontally separately from the NATS. NATS supports [clustering](https://docs.nats.io/nats-server/configuration/clustering) which we have not been using. Ideally, this should be deployed like so:
- Horizontally scalable auth service
- Clustered NATS
- Some type of load balancer on the service

We will probably need to change some application code if we remove the proxy, but it is not explicitly necessary.

**Comment by sfoxdev** [comment]
To avoid issues on deployment we need to change workflow configuration.

For monitoring we can use Prometheus + Grafana + Alertmanager-discord.
