### ISSUE TITLE
xud wishlist

### ISSUE THREAD

**Issue by erkarl** [connext/vector#73]
- [x] prod deployment (ability to run node and router-node on separate machines)
- [ ] ability set node mnemonic during runtime
- [x] hashlock-transfer timelock
- [x] hashlock-status endpoint
  - [x] needs `expired: true | false` field
- [x] cancel transfer endpoint
- [x] onchain balances
- [x] expose ethprovider proxy
- [ ] request collateral

**Comment by rhlsthrm** [comment]
Made specific issues for the remaining items:

#86 
#87
