### ISSUE TITLE
[docs] router readme - add information about collateralization

### ISSUE THREAD

**Issue by ditchfieldcaleb** [connext/vector#81]
[https://github.com/connext/vector/tree/master/modules/router](https://github.com/connext/vector/tree/master/modules/router)

The readme here references collateral in several contexts, as well as "executing collateralization", but the term is not defined, nor its function and purpose defined. Anything that a router operator should know about re:collateral should probably also be documented.

**Comment by rhlsthrm** [comment]
Should be present in the new docs.
