### ISSUE TITLE
[vector-types, server-node, browser-node] rename ServerNodeParams, ServerNodeResponses (and anything else used by both server & browser nodes) to something more generic

### ISSUE THREAD

**Issue by ditchfieldcaleb** [connext/vector#88]
https://github.com/connext/vector/blob/be2834a7bf1af931594ea575a51c96c9ee356b06/modules/browser-node/src/index.ts#L16

The BrowserNode imports & uses `ServerNodeParams` & `ServerNodeResponses`; to keep naming scope correct, they should be changed to something more generic (and anything else that is named for the server and used in both, if they exist)

**Comment by rhlsthrm** [comment]
Thanks for reporting this! Fixed.
